import path from "node:path";
export const STATIC_NAME = "static";
export const ROOT_DIR = path.resolve(import.meta.dirname, "..");
export const DIST_DIR = path.resolve(ROOT_DIR, "./lib");
export const SERVER_ENVIRONMENT_NAME = "server";
export const CLIENT_ENVIRONMENT_NAME = "client";
export const SERVER_ENTRY_NAME = "main";
export const CLIENT_ENTRY_NAME = "index";
export const SERVER_ENTRY_PATH = path.resolve(ROOT_DIR, `./src/${SERVER_ENVIRONMENT_NAME}/${SERVER_ENTRY_NAME}.ts`);
export const CLIENT_ENTRY_PATH = path.resolve(ROOT_DIR, `./src/${CLIENT_ENVIRONMENT_NAME}/${CLIENT_ENTRY_NAME}.ts`);
export const HTML_TEMPLATE_PATH = path.resolve(ROOT_DIR, `./public/index.html`);
export const FAVICON_PATH = path.resolve(ROOT_DIR, "./public/favicon.ico");
